version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    ignore:
      - dependency-name: "chai"
        versions: ">= 4"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "1.x.x"
    labels:
      - "dependencies"
      - "1.x.x"
    ignore:
      - dependency-name: "@types/mocha"
        versions: ">= 9"
      - dependency-name: "@types/node"
        versions: ">= 17"
      - dependency-name: "chai"
        versions: ">= 4"
      - dependency-name: "eslint"
        versions: ">= 7"
      - dependency-name: "mocha"
        versions: ">= 9"
      - dependency-name: "rimraf"
        versions: ">= 3"
      - dependency-name: "typescript"
        versions: ">= 4"
