# This Continous Integration (CI) pipeline lints, builds, and tests the code when a Pull Request is
# created or a commit is pushed to a Prod branch

name: CI
on:
  push:
    branches: [ "master", "1.x.x" ]
  pull_request:
    branches: [ "master", "1.x.x" ]

jobs:
  continous-integration:
    name: Continous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Node Version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Unit Tests
        run: npm test
