name: Node CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.23.0, 14.x, lts/*]

    steps:
<<<<<<< HEAD:.github/workflows/nodejs.yml
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run lint
        npm run build
        npm test
      env:
        CI: true
=======
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm ci
          npm run lint
          npm run build
          npm test
        env:
          CI: true
>>>>>>> f0792cd (Update CI workflow to run on pull requets):.github/workflows/ci.yml
